# Generated by Django 4.2.7 on 2023-12-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnld',
            name='author',
            field=models.CharField(max_length=100, verbose_name='Заголовок статьи'),
        ),
    ]
